name: APK Build
on: 
  push:
    branches:
      - master

  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          chmod +x gradlew
          ./gradlew build
