name: APK Build
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: |
          chmod +x gradlew
          ./gradlew build
